### ISSUE TITLE
Polymer Japan Meetup #0「Polymer/Web Componentsとは何か」

### ISSUE THREAD

**Issue by kazu80** [Polymer-Japan/event#4]
@sizuhiko 

前半のセッションにおいて、岸田さんの[Polymer/Web Componentsとは何か](https://github.com/Polymer-Japan/event/blob/master/2017-10-14/intro-polymer-webcomponents.md)の部分と、私の担当する[なぜPolymerを使うのか](https://github.com/Polymer-Japan/event/blob/master/2017-10-14/why-use-polymer.md)において、内容が被っている箇所があることに対するすり合わせです。

懸念としては、聞いている人に同じ内容を伝えるのはどおなんだろう。。。という事です。

被っている対象の箇所としては、私の受け持っている部分で、なぜPolymer・・・に入る前に、WebComponentの意義を説いているのですが、その箇所になります。

私の意見としては、岸田さんの部分と私の部分は、たしかに被っているのですが、状況が違うのでこのままで大丈夫と思いますが、いかがでしょうか？

**Comment by sizuhiko** [comment]
私が Web Components についていいたいのは、それ前からできていたけど、プラットフォーム（ブラウザネイティブ）だと何がいいの？ということです。
 @monkick の説明はどういう箇所をWeb Componentsにしたら良いか、という話になっていると思いますので、その意図であれば大丈夫かな、と思っています

**Comment by kazu80** [comment]
@sizuhiko 
おすおす。
それでは、今回はこちらで行ってみましょう！スライド作る時間を捻出しないと。。。
